server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Identity-Service

  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: "admin"
    password: "Sikido@123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  jwt:
    signerKey: "E4+rLfKyvXCn10Ol6IVIfRF5q2m3AUQUfHLnUykAkGZV6FVx2S43vZk054hTspSLW+QMWWKbQMFxfvFbF3o3oUGbmpXUxe1Gzg8o4Qj8Ri8IduyG2cFySOq9MsPheaG+bVdpucZ9Z3YS4SLL4SebErKTDAVJT/+09dUb3fChF2o="

  outbound:
    identity:
      client-id: "208388951287-58a9gj7iem7r6k8vdviervjridbni88g.apps.googleusercontent.com"
      client-secret: "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"
      redirect-uri: "http://localhost:3000/authentication"