server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: Identity-Service

  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: "admin"
    password: "Sikido@123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true

  jwt:
    signerKey: "dm90ZXJ1YmJlZHRyb29wc2tuZXd3cml0ZWhpbXNlbGZzbWFsbGVyZHJpdmVybWFueXNvbWVob3dwYXRocmVnaQ=="